# These are data:
ADMIN_URL: https://adminjalin-stg.ottopoint.id/#/login
PARTNER_URL: https://clientjalin-stg.ottopoint.id/#/login
NASABAH_URL: https://jalin-stg.ottopoint.id/auth/login

# Admin login
ADMIN_USER: automation.admin
ADMIN_PASS: P@ssword123

# Partner login
PARTNER_USER: arief.setiawan
PARTNER_PASS: Burungmp2000%

# Nasabah login
NASABAH_URL: 85771064476
NASABAH_PIN: 111111


